### ISSUE TITLE
string primary key - null identity problem in BulkInsert

### ISSUE THREAD

**Issue by TahaBerkay** [zzzprojects/EntityFramework-Extensions#412]
The table has a string primary key and identity when I call BulkInsert,
it throws an exception like:
Cannot insert the value NULL into column 'CustomerID', table 'db_790c5be38e8d41298b9f0f64fb545114.dbo.Customers'; column does not allow nulls. UPDATE fails.

Note: in the object list, every entity id has no value.

I also use the following annotations, but nothing has changed:
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
[Key]

e.g. just change the CustomerID from int to string to reproduce the issue:
https://dotnetfiddle.net/n0p2IF

I would like to have all string identity primary keys be auto-generated from the bulk-insert operation.
InsertKeepIdentity = false didn't help too.

I have the same issues in my local projects when I use BulkInsert without setting the string identities that I want. 
On the other hand, EF Core Add+SaveChanges works well with no issues.

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

You are right, EF Core `SaveChanges` (as well as `BulkSaveChanges`) work correctly for this scenario.

It generates a random `Guid` and stores the value in this column

One problem with your request is that we try to add the minimum logic for the `BulkInsert` to make it as fast as possible. Every check (if the value is null or empty) adds an additional check with some performance cost.

I will check with my developer tomorrow how we could/if we should handle string property that is a key/identity

Meanwhile, I recommend you to use `BulkSaveChanges` if you can. It was already working on my test.

Best Regards,

Jon

**Comment by TahaBerkay** [comment]
Hello,

I have just started to get the following exception even though I use the Fiddle example above on my local project (using int as primary key - identity):
"Violation of PRIMARY KEY constraint ... Cannot insert duplicate key in object ... The duplicate key value is (0)."

**Comment by TahaBerkay** [comment]
Any updates on it?

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

My developer may have fixed it.

I'm supposed to make the code review tomorrow but he told me that the current branch he created might be a little bit complex to merge.

I should be able to give you a better update very soon.

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

We currently do a few more changes to our fix to improve it.

But it should definitively be part of the next release that will be made next Monday (May 31).

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

The v5.1.39 has been released.

There is still some improvement to make on our side but everything should now work with this version.

Could you try it and let us know if we successfully fixed it?

Best Regards,

Jon

**Comment by TahaBerkay** [comment]
I'm still getting the same issue here: https://dotnetfiddle.net/n0p2IF
I will also try to run the latest version using my local project asap.

**Comment by JonathanMagnan** [comment]
Thank you,

You are right, I also keep getting it.

I will look at it and check if something from the fix of my developer has been wrongly merged.

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

After review, I was wrong and the fix of my developer seems to works.

I forget to add the `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` annotation.

Everything seem to work: https://dotnetfiddle.net/m6U2w9

Without this annotation, even the `SaveChanges` doesn't work.

Do you have an example of a scenario where `SaveChanges` works but not our library?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

Since our last conversation, we haven't heard from you.

Did you get the chance to find an example of a scenario where `SaveChanges` works but not our library?

Don't hesitate to contact us, 

Jon

**Comment by TahaBerkay** [comment]
https://dotnetfiddle.net/m6U2w9 seems to give some compile errors. Would you check this out? 
Btw, I will give it a try on my local project tomorrow.

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

Yes, sometimes .NET Fiddle is down on .NET Core, we currently investigate this issue as this is related with `NuGet` package.

The docker server has been restarted so it's currently working.

**Comment by TahaBerkay** [comment]
Looks OK now, thanks

**Comment by JonathanMagnan** [comment]
Hello @TahaBerkay ,

This issue will be closed since we haven't heard back from you.

However, don't hesitate to contact us once you'll be able to provide a project!.

Best Regards,

Jon
